version: '3'

services:

  jaffle-job-postgres:
    image: postgres:latest
    container_name: jaffle-job-postgres-db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
